
version: 2

models:
    - name: covid_19_cases_per_day
      description: "A starter dbt model"
      columns:
          - name: day
            description: "Day"
            tests:
                - unique
                - not_null
          - name: cases
            description: "Daily covid19 cases in Uk"
        