
version: 2

models:
    - name: covid_19_cases_per_day
      description: "A view with UK covid-19 cases by day"
      columns:
          - name: day
            description: "Day"
            tests:
                - unique
                - not_null
          - name: cases
            description: "Number of covid-19 cases"
        