dev:
  target: covid19_dev
  outputs:
    covid19_dev:
      type: postgres
      host: "localhost"
      user: "covid19_user"
      pass: "covid19_password"
      port: 5434
      schema: "public"
      dbname: "covid19_dev"
      threads: 1

test:
  target: covid19_test
  outputs:
    covid19_test:
      type: postgres
      host: "localhost"
      user: "covid19_user"
      pass: "covid19_password"
      port: 5434
      schema: "public"
      dbname: "covid19_test"
      threads: 1
