dev:
  target: covid19_dev
  outputs:
    covid19_dev:
      type: postgres
      host: "postgres-postgresql"
      user: "covid19_user"
      pass: "covid19_password"
      port: 5432
      schema: "public"
      dbname: "covid19_dev"
      threads: 1
