apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "{{ .Release.Name }}"
  namespace: argo
spec:
  entrypoint: ingestion
  serviceAccountName: argo
  arguments:
    parameters:
      - name: start-date
        value: "2020-01-01"
      - name: end-date
        value: "2020-01-02"
  templates:
    - name: ingestion
      steps:
        - - name: ExtractAndLoad
            template: covid19-uk
        - - name: dbt-run
            template: dbt-run    
    - name: covid19-uk
      container:
        name: covid19ukingestions
        image: "{{ .Values.ingestion.image }}"
        imagePullPolicy: Never
        command: [java]
        args:
          [
            "-jar",
            "covid19-uk-ingestions.jar",
            "{{ .Values.environment }}",
            "--start-date",
            "{{`{{workflow.parameters.start-date}}`}}",
            "--end-date",
            "{{`{{workflow.parameters.end-date}}`}}",
          ]
    - name: dbt-run
      container:
        name: dbt-run
        image: "{{ .Values.transformation.image }}"
        imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
          - >-
            dbt run --project-dir data-models --profiles-dir resources/ --profile {{ .Values.environment }} &&
            dbt test --project-dir data-models --profiles-dir resources/ --profile {{ .Values.environment }}  --schema
