apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: db-migrations-{{ .Values.environment }}
  namespace: argo
  name: "{{ .Release.Name }}-{{ .Values.environment }}"
spec:
  entrypoint: db-migrations
  serviceAccountName: argo
  templates:
    - name: db-migrations
      container:
        name: db-migrations
        image: "{{ .Values.image }}"
        imagePullPolicy: Never
        command: [java]
        args:
          [
            "-jar",
            "db-migrations.jar",
            "{{ .Values.environment }}"
          ]